import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/app/global.css';
import { cn } from '@/app/lib/ui/tw';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-next',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const bodyClass = cn(geistSans.variable, 'bg-grayscale-50 font-sans antialiased');

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={bodyClass}>{children}</body>
    </html>
  );
}
